name: validate
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - release-*
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt -q update
          sudo apt -q install libseccomp-dev
      - uses: golangci/golangci-lint-action@v2
        with:
          # must be specified without patch version
          version: v1.41


